"""Add player_class column to Player table

Revision ID: c580da24a097
Revises: e84d8cb2b6bd
Create Date: 2024-11-10 09:57:14.658106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c580da24a097'
down_revision: Union[str, None] = 'e84d8cb2b6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Player', sa.Column('player_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Player', 'player_class')
    # ### end Alembic commands ###
